### ISSUE TITLE
Design Homepage

### ISSUE THREAD

**Issue by forthright48** [forthright48/website-v3#10]
Acceptance Criteria:
- [x] Complete the issues inside the epic ( excluded in estimate )
- [x] Use simplecss for design
- [x] Title
- [x] Small introduction as body. Must be centered vertically.
